# Generated by Django 5.2.13 on 2026-08-26 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Use o formato: '+5511999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
