# Generated by Django 5.2.13 on 2026-07-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cardápio')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='core.evento')),
                ('pratos', models.ManyToManyField(blank=True, to='core.prato')),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápios',
            },
        ),
    ]
