# Generated by Django 5.2.13 on 2026-07-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardapio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='ingredienteprato',
            name='quantidade',
        ),
    ]
