# Generated by Django 5.2.13 on 2026-05-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_endereco_utensilio_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='utensilio',
            options={'verbose_name': 'Utensílio', 'verbose_name_plural': 'Utensílios'},
        ),
    ]
