# Generated by Django 5.2.13 on 2026-08-27 14:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR'),
        ),
    ]
