# Generated by Django 5.2.13 on 2026-08-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='estoque',
        ),
        migrations.AddField(
            model_name='estoque',
            name='ingrediente',
            field=models.OneToOneField(default='sem ingrediente', on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='core.ingrediente'),
            preserve_default=False,
        ),
    ]
