# Generated by Django 5.2.13 on 2026-05-11 16:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipoevento_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoevento',
            name='cor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
