# Generated by Django 5.2.13 on 2026-09-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ingrediente_estoque_estoque_ingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='funcionario',
        ),
    ]
