# Generated by Django 5.2.13 on 2026-09-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convite',
        ),
    ]
