# Generated by Django 5.2.12 on 2026-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(upload_to='funcionarios/')),
            ],
        ),
    ]
