# Generated by Django 5.2.13 on 2026-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_prato'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria do Prato',
                'verbose_name_plural': 'Categorias do Pratos',
            },
        ),
    ]
