# Generated by Django 5.2.13 on 2026-05-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoriaprato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprato',
            options={'verbose_name': 'Categoria do Prato', 'verbose_name_plural': 'Categorias dos Pratos'},
        ),
    ]
