# Generated by Django 5.2.13 on 2026-05-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_itemcompra'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria do Ingrediente',
                'verbose_name_plural': 'Categorias dos Ingredientes',
            },
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='nome',
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='und',
            field=models.CharField(default='un', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
