# Generated by Django 5.2.13 on 2026-05-29 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categoriaingrediente_remove_estoque_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.tipoevento'),
        ),
        migrations.AddField(
            model_name='prato',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoriaprato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.endereco'),
        ),
        migrations.CreateModel(
            name='EquipeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_vinculados', to='core.evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_vinculadas', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Equipe de Evento',
                'verbose_name_plural': 'Equipes de Evento',
                'unique_together': {('funcionario', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='equipe_evento',
            field=models.ManyToManyField(related_name='eventos', through='core.EquipeEvento', to='core.funcionario'),
        ),
        migrations.CreateModel(
            name='IngredientePrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingrediente')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prato')),
            ],
            options={
                'verbose_name': 'Ingrediente do Prato',
                'verbose_name_plural': 'Ingredientes dos Pratos',
                'unique_together': {('prato', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='prato',
            name='ingredientes',
            field=models.ManyToManyField(through='core.IngredientePrato', to='core.ingrediente'),
        ),
        migrations.CreateModel(
            name='OrcamentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mao_de_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='core.evento')),
            ],
            options={
                'verbose_name': 'Orçamento do Evento',
                'verbose_name_plural': 'Orçamentos dos Eventos',
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos_vinculados', to='core.evento')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_vinculados', to='core.prato')),
            ],
            options={
                'verbose_name': 'Prato do Evento',
                'verbose_name_plural': 'Pratos do Evento',
                'unique_together': {('evento', 'prato')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='cardapio',
            field=models.ManyToManyField(related_name='eventos', through='core.Cardapio', to='core.prato'),
        ),
        migrations.CreateModel(
            name='UtensilioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utensilios_vinculados', to='core.evento')),
                ('utensilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_vinculados', to='core.utensilio')),
            ],
            options={
                'verbose_name': 'Utensilio do Evento',
                'verbose_name_plural': 'Utensilios do Evento',
                'unique_together': {('evento', 'utensilio')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='utensilio_evento',
            field=models.ManyToManyField(related_name='eventos', through='core.UtensilioEvento', to='core.utensilio'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
