# Generated by Django 5.2.13 on 2026-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_evento_tipo_evento_prato_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='nome',
            field=models.CharField(default='campo vazio', max_length=100),
            preserve_default=False,
        ),
    ]
