# Generated by Django 5.2.13 on 2026-06-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_estoque_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='und',
        ),
        migrations.AddField(
            model_name='estoque',
            name='und_medida',
            field=models.CharField(default='', max_length=20, verbose_name='Unidade de Medida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaprato',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Item'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
