# Generated by Django 5.2.13 on 2026-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
