# Generated by Django 5.2.13 on 2026-06-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ingrediente_quantidade_alter_ingrediente_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipeevento',
            options={'verbose_name': 'Equipe do Evento', 'verbose_name_plural': 'Equipes do Evento'},
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.cliente'),
        ),
    ]
