# Generated by Django 5.2.13 on 2026-07-09 03:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_equipeevento_options_evento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='sem telefone', max_length=128, region='BR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='sem telefone', max_length=128, region='BR'),
            preserve_default=False,
        ),
    ]
